"use client";

import { useEffect, useMemo, useState } from "react";
import { PageHeader } from "@/components/ui/page-header";
import { KpiCard } from "@/components/ui/kpi-card";
import { graphqlRequest } from "@/lib/api-client";
import { useAdminData } from "@/components/admin/admin-data-provider";

type Point={date:string;value:number}; type Metric={label:string;value:number};
type Analytics={userGrowth:Point[];sellerGrowth:Point[];listingGrowth:Point[];revenue:Point[];categoryDistribution:Metric[];planDistribution:Metric[];verificationOutcomes:Metric[];reportOutcomes:Metric[];billingActivity:Metric[];health:{paymentSuccessPercent:number;openReportRatePercent:number;activeListingPercent:number;activeSellerPercent:number}};
const QUERY=`query AdminAnalytics($days:Int!){adminAnalytics(days:$days){userGrowth{date value} sellerGrowth{date value} listingGrowth{date value} revenue{date value} categoryDistribution{label value} planDistribution{label value} verificationOutcomes{label value} reportOutcomes{label value} billingActivity{label value} health{paymentSuccessPercent openReportRatePercent activeListingPercent activeSellerPercent}}}`;
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v).replace(/\u00a0/g," ");

export default function AnalyticsPage(){
  const {toast}=useAdminData(); const [days,setDays]=useState(30); const [data,setData]=useState<Analytics|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;(async()=>{try{const result=await graphqlRequest<{adminAnalytics:Analytics}>(QUERY,{days});if(active)setData(result.adminAnalytics);}catch(e){if(active)toast("Analytics unavailable",e instanceof Error?e.message:undefined,"danger");}finally{if(active)setLoading(false);}})();return()=>{active=false}},[days,toast]);
  const totals=useMemo(()=>data?{users:data.userGrowth.reduce((s,p)=>s+p.value,0),sellers:data.sellerGrowth.reduce((s,p)=>s+p.value,0),listings:data.listingGrowth.reduce((s,p)=>s+p.value,0),revenue:data.revenue.reduce((s,p)=>s+p.value,0)}:{users:0,sellers:0,listings:0,revenue:0},[data]);
  function choose(value:number){setLoading(true);setDays(value)}
  return <div className="space-y-6"><PageHeader title="Analytics" description="Marketplace growth, revenue, trust and billing performance from backend aggregates." actions={<div className="inline-flex rounded-lg border border-slate-200 bg-white p-1">{[7,30,90].map((value)=><button key={value} type="button" onClick={()=>choose(value)} className={`rounded-md px-3 py-1.5 text-xs font-bold ${days===value?"bg-emerald-600 text-white":"text-slate-500 hover:bg-slate-50"}`}>{value} days</button>)}</div>}/>
    {loading&&!data?<div className="rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading analytics…</div>:data?<>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="New users" value={Math.round(totals.users).toLocaleString("pt-BR")} change={`${days} days`} meta="Account growth"/><KpiCard label="New sellers" value={Math.round(totals.sellers).toLocaleString("pt-BR")} change={`${days} days`} meta="Seller growth"/><KpiCard label="New listings" value={Math.round(totals.listings).toLocaleString("pt-BR")} change={`${days} days`} meta="Listing growth"/><KpiCard label="Revenue" value={money(totals.revenue)} change={`${days} days`} meta="Paid seller services"/></div>
      <div className="grid gap-6 xl:grid-cols-2"><SeriesCard title="Marketplace growth" series={[{label:"Users",rows:data.userGrowth},{label:"Sellers",rows:data.sellerGrowth},{label:"Listings",rows:data.listingGrowth}]}/><SeriesCard title="Revenue trend" currency series={[{label:"Revenue",rows:data.revenue}]}/></div>
      <div className="grid gap-6 lg:grid-cols-2 xl:grid-cols-3"><MetricCard title="Top categories" rows={data.categoryDistribution}/><MetricCard title="Seller plans" rows={data.planDistribution}/><MetricCard title="Billing activity" rows={data.billingActivity}/><MetricCard title="Verification outcomes" rows={data.verificationOutcomes}/><MetricCard title="Report outcomes" rows={data.reportOutcomes}/><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Marketplace health</h2><p className="mt-0.5 text-xs text-slate-500">Current operational ratios</p><div className="mt-5 space-y-4"><Health label="Payment success" value={data.health.paymentSuccessPercent}/><Health label="Active listings" value={data.health.activeListingPercent}/><Health label="Active sellers" value={data.health.activeSellerPercent}/><Health label="Open report rate" value={data.health.openReportRatePercent} inverse/></div></section></div>
    </>:<div className="rounded-xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">Analytics could not be loaded.</div>}
  </div>;
}

function SeriesCard({title,series,currency=false}:{title:string;series:{label:string;rows:Point[]}[];currency?:boolean}){const max=Math.max(...series.flatMap((s)=>s.rows.map((p)=>p.value)),1);return <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">{title}</h2><div className="mt-5 space-y-5">{series.map((item)=><div key={item.label}><div className="mb-2 flex items-center justify-between text-xs"><strong>{item.label}</strong><span className="text-slate-400">{currency?money(item.rows.reduce((s,p)=>s+p.value,0)):Math.round(item.rows.reduce((s,p)=>s+p.value,0)).toLocaleString("pt-BR")}</span></div><div className="flex h-28 items-end gap-1 overflow-hidden rounded-lg bg-slate-50 p-2">{item.rows.map((point)=><div key={point.date} title={`${point.date}: ${currency?money(point.value):point.value}`} className="min-w-1 flex-1 rounded-t bg-emerald-500/80" style={{height:`${Math.max(point.value?4:0,Math.round(point.value/max*100))}%`}}/>)}</div><div className="mt-1 flex justify-between text-[9px] text-slate-400"><span>{item.rows[0]?.date||"—"}</span><span>{item.rows.at(-1)?.date||"—"}</span></div></div>)}</div></section>}
function MetricCard({title,rows}:{title:string;rows:Metric[]}){const max=Math.max(...rows.map((r)=>r.value),1);return <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">{title}</h2><div className="mt-5 space-y-3">{rows.length?rows.slice(0,8).map((row)=><div key={row.label}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate text-slate-600">{row.label}</span><strong>{Number.isInteger(row.value)?row.value.toLocaleString("pt-BR"):row.value.toFixed(1)}</strong></div><div className="h-1.5 rounded-full bg-slate-100"><div className="h-1.5 rounded-full bg-emerald-500" style={{width:`${Math.max(row.value?4:0,Math.round(row.value/max*100))}%`}}/></div></div>):<p className="text-xs text-slate-500">No data for this period.</p>}</div></section>}
function Health({label,value,inverse=false}:{label:string;value:number;inverse?:boolean}){const good=inverse?value<5:value>=80;return <div><div className="flex justify-between text-xs"><span className="text-slate-600">{label}</span><strong className={good?"text-emerald-700":"text-slate-900"}>{value.toFixed(1)}%</strong></div><div className="mt-1.5 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-500" style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div></div>}
