"use client";
import { supportTickets } from "@/data/mock-data";
import { PageHeader } from "@/components/ui/page-header";
import { DataTable } from "@/components/ui/data-table";
import { StatusBadge } from "@/components/ui/status-badge";
import { ActionDialog } from "@/components/ui/action-dialog";
import { Icons } from "@/lib/icons";
import { useAdminDemo } from "@/components/admin/admin-demo-provider";
export default function SupportPage(){const {getStatus,setStatus,toast}=useAdminDemo();return <div className="space-y-6"><PageHeader title="Support" description="Triage customer issues and keep response times healthy."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Open tickets","12","4 high priority"],["First response","8m","Target < 15m"],["Resolution time","2h 14m","-18%"],["CSAT","4.7/5","92% positive"]].map(([a,b,c])=><div key={a} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">{a}</p><strong className="mt-2 block text-xl font-black">{b}</strong><p className="mt-1 text-[10px] text-slate-400">{c}</p></div>)}</div><DataTable rows={supportTickets} searchText={t=>`${t.id} ${t.user} ${t.subject} ${t.category} ${t.priority}`} searchPlaceholder="Search ticket, user or subject…" statusOf={t=>getStatus("ticket",t.id,t.status)} statuses={["Open","Review","Resolved"]} selectedLabel="tickets" columns={[
{key:"ticket",label:"Ticket",cell:t=><div><div className="max-w-[300px] truncate font-bold text-slate-900">{t.subject}</div><div className="mt-0.5 text-[10px] text-slate-400">{t.id} · {t.user}</div></div>},{key:"category",label:"Category",cell:t=>t.category},{key:"priority",label:"Priority",cell:t=><span className={`font-black ${t.priority==="High"?"text-red-600":"text-slate-600"}`}>{t.priority}</span>},{key:"updated",label:"Updated",cell:t=>t.updated},{key:"status",label:"Status",cell:t=><StatusBadge status={getStatus("ticket",t.id,t.status)}/>},{key:"action",label:"",cell:t=><ActionDialog trigger={<button type="button" aria-label={`Open support ticket ${t.id}`} className="grid size-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><Icons.chevronRight size={16}/></button>} title={t.subject} description={`${t.id} · ${t.user} · ${t.category}`} confirmLabel="Send reply" reasonLabel="Reply message" reasonPlaceholder="Write a clear response to the customer…" reasonHelp="The customer will receive this message when the support action is submitted." minReasonLength={10} onConfirm={()=>{setStatus("ticket",t.id,"Review");toast("Reply prepared",`Ticket ${t.id} moved to review.`)}} requireReason/>}]}/></div>}
