"use client";

import { useEffect, useState } from "react";
import { AdminButton } from "@/components/ui/admin-button";
import { Icons } from "@/lib/icons";
import { useAdminData } from "@/components/admin/admin-data-provider";
import { ActionDialog } from "@/components/ui/action-dialog";
import { graphqlRequest } from "@/lib/api-client";

type Config={marketplaceName:string;supportEmail:string;allowNewRegistrations:boolean;allowSellerActivation:boolean;maintenanceMode:boolean;automatedListingFlagging:boolean;sellerVerificationRequired:boolean;defaultListingDurationDays:number;maxListingImages:number;highRiskThreshold:number;adminEmailOperationalAlerts:boolean;adminVerificationQueueAlerts:boolean;adminPaymentFailureAlerts:boolean};
type Tab="Platform"|"Marketplace"|"Trust & safety"|"Notifications"|"Admin access";
const CONFIG_QUERY=`query PlatformConfiguration { platformConfiguration { marketplaceName supportEmail allowNewRegistrations allowSellerActivation maintenanceMode automatedListingFlagging sellerVerificationRequired defaultListingDurationDays maxListingImages highRiskThreshold adminEmailOperationalAlerts adminVerificationQueueAlerts adminPaymentFailureAlerts } }`;

function Switch({enabled,onChange,label,disabled=false}:{enabled:boolean;onChange:()=>void;label:string;disabled?:boolean}){return <button type="button" role="switch" aria-checked={enabled} aria-label={label} disabled={disabled} onClick={onChange} className={`relative h-7 w-12 shrink-0 rounded-full border transition disabled:cursor-not-allowed disabled:opacity-60 ${enabled?"border-emerald-600 bg-emerald-600":"border-slate-300 bg-slate-200"}`}><span className={`absolute top-1 size-5 rounded-full bg-white shadow-sm transition ${enabled?"left-6":"left-1"}`}/></button>}

export function SettingsClient(){
  const [tab,setTab]=useState<Tab>("Platform"); const [config,setConfig]=useState<Config|null>(null); const [loading,setLoading]=useState(true);
  const {toast,users}=useAdminData();
  useEffect(()=>{let active=true;(async()=>{try{const data=await graphqlRequest<{platformConfiguration:Config}>(CONFIG_QUERY);if(active)setConfig(data.platformConfiguration);}catch(e){if(active)toast("Settings unavailable",e instanceof Error?e.message:undefined,"danger");}finally{if(active)setLoading(false);}})();return()=>{active=false}},[toast]);
  async function update(input:Record<string,unknown>,success:string){try{const data=await graphqlRequest<{updatePlatformConfiguration:Config}>(`mutation($input:PlatformConfigurationInput!){updatePlatformConfiguration(input:$input){marketplaceName supportEmail allowNewRegistrations allowSellerActivation maintenanceMode automatedListingFlagging sellerVerificationRequired defaultListingDurationDays maxListingImages highRiskThreshold adminEmailOperationalAlerts adminVerificationQueueAlerts adminPaymentFailureAlerts}}`,{input});setConfig(data.updatePlatformConfiguration);toast(success);}catch(e){toast("Setting could not be updated",e instanceof Error?e.message:undefined,"danger");}}
  const tabs:[Tab,typeof Icons.settings][]=[["Platform",Icons.settings],["Marketplace",Icons.store],["Trust & safety",Icons.shield],["Notifications",Icons.bell],["Admin access",Icons.lock]];
  if(loading)return <div className="rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading platform settings…</div>;
  if(!config)return <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">Platform settings could not be loaded for this administrator role.</div>;
  const admins=users.filter((u)=>u.type==="Administrator");
  return <div className="grid gap-6 xl:grid-cols-[240px_1fr]">
    <aside className="self-start rounded-xl border border-slate-200 bg-white p-2 xl:sticky xl:top-24">{tabs.map(([label,Icon])=><button key={label} type="button" onClick={()=>setTab(label)} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-xs font-bold ${tab===label?"bg-emerald-50 text-emerald-900":"text-slate-600 hover:bg-slate-50"}`}><Icon size={16}/>{label}</button>)}</aside>
    <div className="space-y-6">
      {tab==="Platform"&&<section className="rounded-xl border border-slate-200 bg-white"><Head title="Platform information" desc="Core Marketlift configuration."/><div className="p-5"><dl className="overflow-hidden rounded-xl border border-slate-200"><ReadOnlySetting label="Platform name" value={config.marketplaceName}/><ReadOnlySetting label="Support address" value={config.supportEmail}/><ReadOnlySetting label="Listing duration" value={`${config.defaultListingDurationDays} days`}/><ReadOnlySetting label="Maximum listing images" value={String(config.maxListingImages)}/><ReadOnlySetting label="High-risk threshold" value={`${config.highRiskThreshold}%`} last/></dl></div></section>}
      {tab==="Marketplace"&&<section className="rounded-xl border border-slate-200 bg-white"><Head title="Marketplace controls" desc="Control onboarding and marketplace availability."/><div className="divide-y divide-slate-100 px-5"><Toggle title="User registration" description="Allow new users to create Marketlift accounts." enabled={config.allowNewRegistrations} action={()=>void update({allowNewRegistrations:!config.allowNewRegistrations},"User registration setting updated")}/><Toggle title="Seller activation" description="Allow eligible users to activate selling." enabled={config.allowSellerActivation} action={()=>void update({allowSellerActivation:!config.allowSellerActivation},"Seller activation setting updated")}/><StatusRow title="Marketplace availability" description="Current public marketplace availability." value={config.maintenanceMode?"Maintenance":"Online"} tone={config.maintenanceMode?"danger":"success"}/></div></section>}
      {tab==="Trust & safety"&&<div className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white"><Head title="Trust & safety controls" desc="Moderation safeguards and seller verification policy."/><div className="divide-y divide-slate-100 px-5"><Toggle title="Automated listing flagging" description="Send high-risk marketplace content to moderation review." enabled={config.automatedListingFlagging} action={()=>void update({automatedListingFlagging:!config.automatedListingFlagging},"Automated listing flagging updated")}/><Toggle title="Require seller verification" description="Require identity verification for protected seller capabilities." enabled={config.sellerVerificationRequired} action={()=>void update({sellerVerificationRequired:!config.sellerVerificationRequired},"Seller verification policy updated")}/></div></section><section className="rounded-xl border border-red-200 bg-red-50/25 p-5"><div className="flex items-start gap-3"><Icons.alert className="mt-0.5 shrink-0 text-red-700" size={18}/><div className="flex-1"><h2 className="text-sm font-black text-red-950">Danger zone</h2><p className="mt-1 text-xs leading-5 text-red-900/70">These actions affect platform availability or active sessions. A written reason is required.</p><div className="mt-4 flex flex-wrap gap-2"><ActionDialog trigger={<AdminButton variant={config.maintenanceMode?"outline":"danger"}>{config.maintenanceMode?"Disable maintenance mode":"Enable maintenance mode"}</AdminButton>} title={config.maintenanceMode?"Disable maintenance mode?":"Enable maintenance mode?"} description={config.maintenanceMode?"Public marketplace access will be restored.":"Public marketplace access will be temporarily unavailable."} confirmLabel={config.maintenanceMode?"Restore marketplace":"Enable maintenance"} tone={config.maintenanceMode?"primary":"danger"} requireReason onConfirm={()=>void update({maintenanceMode:!config.maintenanceMode},config.maintenanceMode?"Marketplace restored":"Maintenance mode enabled")}/><ActionDialog trigger={<AdminButton variant="outline">Invalidate all sessions</AdminButton>} title="Invalidate all sessions?" description="All users and administrators will need to sign in again." confirmLabel="Invalidate sessions" tone="danger" requireReason onConfirm={(reason)=>void (async()=>{try{const d=await graphqlRequest<{invalidateAllSessions:number}>(`mutation($reason:String!){invalidateAllSessions(reason:$reason)}`,{reason});toast("Sessions invalidated",`${d.invalidateAllSessions} active session${d.invalidateAllSessions===1?"":"s"} invalidated.`,"danger");location.assign("/login");}catch(e){toast("Session reset failed",e instanceof Error?e.message:undefined,"danger");}})()}/></div></div></div></section></div>}
      {tab==="Notifications"&&<section className="rounded-xl border border-slate-200 bg-white"><Head title="Administrator notifications" desc="Choose which operational events should alert administrators."/><div className="divide-y divide-slate-100 px-5"><Toggle title="Email operational alerts" description="Receive high-priority operational alerts by email." enabled={config.adminEmailOperationalAlerts} action={()=>void update({adminEmailOperationalAlerts:!config.adminEmailOperationalAlerts},"Operational email alerts updated")}/><Toggle title="Verification queue alerts" description="Alert administrators about verification backlog." enabled={config.adminVerificationQueueAlerts} action={()=>void update({adminVerificationQueueAlerts:!config.adminVerificationQueueAlerts},"Verification alerts updated")}/><Toggle title="Payment failure alerts" description="Alert finance administrators about failed payments." enabled={config.adminPaymentFailureAlerts} action={()=>void update({adminPaymentFailureAlerts:!config.adminPaymentFailureAlerts},"Payment alerts updated")}/></div></section>}
      {tab==="Admin access"&&<section className="rounded-xl border border-slate-200 bg-white"><Head title="Administrator access" desc="Review administrator roles and account status."/><div className="p-5"><div className="table-scroll overflow-hidden rounded-xl border border-slate-200"><table className="admin-table"><thead><tr><th>Administrator</th><th>Email</th><th>Role</th><th>Status</th></tr></thead><tbody>{admins.map((admin)=><tr key={admin.id}><td className="font-bold text-slate-900">{admin.name}</td><td>{admin.email}</td><td>{(admin.adminRole||"admin").replace(/_/g," ")}</td><td><span className={`text-xs font-black ${admin.status==="Active"?"text-emerald-700":"text-red-700"}`}>{admin.status}</span></td></tr>)}{admins.length===0&&<tr><td colSpan={4} className="py-8 text-center text-xs text-slate-500">No administrator accounts are visible to this role.</td></tr>}</tbody></table></div></div></section>}
    </div>
  </div>;
}
function Head({title,desc}:{title:string;desc:string}){return <div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-black text-slate-950">{title}</h2><p className="mt-0.5 text-xs text-slate-600">{desc}</p></div>}
function ReadOnlySetting({label,value,last=false}:{label:string;value:string;last?:boolean}){return <div className={`grid gap-2 px-4 py-4 sm:grid-cols-[190px_1fr] ${last?"":"border-b border-slate-100"}`}><dt className="text-xs font-bold text-slate-700">{label}</dt><dd className="text-sm font-black text-slate-950">{value}</dd></div>}
function Toggle({title,description,enabled,action}:{title:string;description:string;enabled:boolean;action:()=>void}){return <div className="flex items-center justify-between gap-4 py-4"><div><p className="text-xs font-bold text-slate-900">{title}</p><p className="mt-1 text-[11px] leading-4 text-slate-600">{description}</p></div><Switch enabled={enabled} onChange={action} label={title}/></div>}
function StatusRow({title,description,value,tone}:{title:string;description:string;value:string;tone:"success"|"danger"}){return <div className="flex items-center justify-between gap-4 py-4"><div><p className="text-xs font-bold text-slate-900">{title}</p><p className="mt-1 text-[11px] leading-4 text-slate-600">{description}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${tone==="success"?"bg-emerald-50 text-emerald-800":"bg-red-50 text-red-800"}`}>{value}</span></div>}
