"use client";
import { listings } from "@/data/mock-data";
import { PageHeader } from "@/components/ui/page-header";
import { DataTable } from "@/components/ui/data-table";
import { StatusBadge } from "@/components/ui/status-badge";
import { ActionDialog } from "@/components/ui/action-dialog";
import { SafeLink } from "@/components/ui/safe-link";
import { Icons } from "@/lib/icons";
import { useAdminDemo } from "@/components/admin/admin-demo-provider";
const flagged=listings.filter(l=>l.reports>0||l.status==="Review"||l.status==="Rejected");
export default function ModerationPage(){const {getStatus,setStatus}=useAdminDemo();return <div className="space-y-6"><PageHeader title="Moderation" description="Review flagged listings and enforce marketplace policy consistently."/><div className="rounded-xl border border-amber-200 bg-amber-50/60 p-4"><div className="flex items-start gap-3"><Icons.shield size={18} className="mt-0.5 text-amber-700"/><div><p className="text-xs font-black text-amber-950">Moderation decisions require context</p><p className="mt-1 text-xs leading-5 text-amber-800/70">Reject and remove decisions require an internal reason so enforcement remains explainable and auditable.</p></div></div></div><DataTable rows={flagged} searchText={l=>`${l.id} ${l.title} ${l.seller} ${l.category}`} searchPlaceholder="Search moderation queue…" statusOf={l=>getStatus("listing",l.id,l.status)} statuses={["Review","Rejected","Active"]} selectedLabel="flagged listings" columns={[
{key:"listing",label:"Listing",cell:l=><div><div className="max-w-[300px] truncate font-bold text-slate-900">{l.title}</div><div className="mt-0.5 text-[10px] text-slate-400">{l.id} · {l.seller}</div></div>},{key:"category",label:"Category",cell:l=>l.category},{key:"reports",label:"Reports",cell:l=><span className="font-black text-red-600">{l.reports}</span>},{key:"status",label:"Status",cell:l=><StatusBadge status={getStatus("listing",l.id,l.status)}/>},{key:"actions",label:"Decision",cell:l=><div className="flex items-center gap-1.5"><ActionDialog trigger={<button className="rounded-lg bg-emerald-50 px-2.5 py-1.5 text-[11px] font-black text-emerald-700 hover:bg-emerald-100">Approve</button>} title="Approve listing?" description="This returns the listing to the active marketplace." confirmLabel="Approve" onConfirm={()=>setStatus("listing",l.id,"Active",`${l.id} approved`)}/><ActionDialog trigger={<button className="rounded-lg bg-red-50 px-2.5 py-1.5 text-[11px] font-black text-red-700 hover:bg-red-100">Reject</button>} title="Reject listing?" description="The listing will remain unavailable and the reason will be retained in the moderation experience." confirmLabel="Reject" tone="danger" requireReason onConfirm={()=>setStatus("listing",l.id,"Rejected",`${l.id} rejected`)}/><SafeLink href={`/listings/${l.id}`} aria-label={`Review ${l.title}`} className="grid size-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><Icons.eye size={15}/></SafeLink></div>}]}/></div>}
