"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { SafeLink } from "@/components/ui/safe-link";
import { LiveStatusBadge } from "@/components/ui/live-status-badge";
import { EntityActions, MoveListingToReviewAction } from "@/components/admin/entity-actions";
import { MarketplaceImage } from "@/components/admin/marketplace-image";
import { PublicListingLink, PublicSellerLink } from "@/components/admin/public-marketplace-link";
import { useAdminData } from "@/components/admin/admin-data-provider";
import { graphqlRequest } from "@/lib/api-client";
import type { Status } from "@/types/admin";

type Listing={id:string;slug:string;title:string;description:string;price:number|null;category:string;categoryName:string;condition:string|null;location:{state:string;stateCode:string;city:string;district:string|null};images:string[];seller:{id:string;name:string};createdAt:string;status:string;sellerDeletedAt:string|null;views:number;favorites:number;inquiries:number;featured:boolean;urgent:boolean};
const QUERY=`query AdminListingDetail($id:String!){adminListing(id:$id){id slug title description price category categoryName condition location{state stateCode city district} images seller{id name} createdAt status sellerDeletedAt views favorites inquiries featured urgent}}`;
const fmt=(value:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const money=(value:number|null)=>value==null?"—":new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value);
const title=(v:string)=>v.replace(/_/g," ").replace(/\b\w/g,(c)=>c.toUpperCase());
const uiStatus=(listing:Listing):Status=>listing.sellerDeletedAt?"Deleted":({published:"Active",under_review:"Review",rejected:"Rejected",removed:"Removed",draft:"Draft",paused:"Paused",sold:"Sold",expired:"Expired"}[listing.status]||title(listing.status)) as Status;
const location=(l:Listing)=>[l.location.district,l.location.city,l.location.stateCode||l.location.state].filter(Boolean).join(", ")||"—";

export default function ListingDetailPage(){
  const {listingId}=useParams<{listingId:string}>(); const {toast,reports,moderationCases}=useAdminData(); const [listing,setListing]=useState<Listing|null>(null); const [loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{const d=await graphqlRequest<{adminListing:Listing|null}>(QUERY,{id:listingId});setListing(d.adminListing);}catch(e){toast("Listing unavailable",e instanceof Error?e.message:undefined,"danger");}finally{setLoading(false)}},[listingId,toast]);
  useEffect(()=>{const timeoutId=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timeoutId)},[load]);
  if(loading)return <div className="rounded-xl border bg-white p-8 text-sm text-slate-500">Loading listing…</div>;
  if(!listing)return <div className="rounded-xl border bg-white p-8 text-center"><h1 className="text-lg font-black">Listing not found</h1><SafeLink href="/listings" className="mt-4 inline-flex text-sm font-bold text-emerald-700">Back to listings</SafeLink></div>;
  const status=uiStatus(listing); const relatedReports=reports.filter((r)=>r.type==="Listing"&&r.targetId===listing.id); const moderation=moderationCases.find((m)=>m.listingId===listing.id);
  return <div className="space-y-6"><SafeLink href="/listings" className="text-xs font-bold text-slate-500">← Back to listings</SafeLink>
    <div className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-xl font-black text-slate-950">{listing.title}</h1><LiveStatusBadge kind="listing" id={listing.id} status={status}/></div><p className="mt-1 text-xs text-slate-500">{listing.id} · {listing.categoryName} · {fmt(listing.createdAt)}</p></div><EntityActions kind="listing" id={listing.id} name={listing.title} status={status} publicSlug={listing.slug}/></div>
    <div className="grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><section className="space-y-6"><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="grid gap-2 p-4 sm:grid-cols-2">{listing.images.length?listing.images.map((src,index)=><MarketplaceImage key={src+index} src={src} alt={`${listing.title} image ${index+1}`} className="h-60 w-full rounded-lg object-cover" fallbackClassName="h-60 w-full rounded-lg"/>):<div className="grid h-60 place-items-center rounded-lg bg-slate-100 text-sm text-slate-400">No images</div>}</div><div className="border-t border-slate-100 p-5"><h2 className="text-sm font-black">Listing content</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{listing.description}</p></div></div>
      <div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Moderation history</h2>{moderation?<div className="mt-4 space-y-3 text-xs"><Row label="Case status" value={title(moderation.status)}/><Row label="Source" value={title(moderation.source)}/><Row label="Review reason" value={moderation.reviewReason}/><Row label="Decision reason" value={moderation.decisionReason||"—"}/><Row label="Opened" value={moderation.openedAt}/><Row label="Decided" value={moderation.decidedAt||"—"}/><Row label="Decided by" value={moderation.decidedBy||"—"}/></div>:<p className="mt-3 text-xs text-slate-500">No moderation case is present in the currently loaded moderation history.</p>}</div></section>
      <aside className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Listing details</h2><div className="mt-4 space-y-4 text-xs"><Row label="Price" value={money(listing.price)}/><Row label="Seller" value={listing.seller.name}/><Row label="Condition" value={listing.condition?title(listing.condition):"—"}/><Row label="Location" value={location(listing)}/><Row label="Views" value={String(listing.views)}/><Row label="Favorites" value={String(listing.favorites)}/><Row label="Inquiries" value={String(listing.inquiries)}/><Row label="Loaded reports" value={String(relatedReports.length)}/>{listing.sellerDeletedAt&&<Row label="Seller deleted" value={fmt(listing.sellerDeletedAt)}/>}</div><div className="mt-5 flex flex-col gap-2">{status!=="Deleted"&&status!=="Removed"&&status!=="Rejected"&&<PublicListingLink title={listing.title} slug={listing.slug}/>}<PublicSellerLink sellerId={listing.seller.id} sellerName={listing.seller.name}/></div></section>
        <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Queue control</h2><p className="mt-2 text-xs leading-5 text-slate-500">Move an eligible listing into moderation when it needs administrator review.</p><div className="mt-4"><MoveListingToReviewAction id={listing.id} status={status}/></div></section>{relatedReports.length>0&&<section className="rounded-xl border border-orange-200 bg-orange-50/40 p-5"><h2 className="text-sm font-black text-orange-950">Loaded related reports</h2><div className="mt-3 space-y-2">{relatedReports.map((r)=><SafeLink key={r.id} href={`/reports/${r.id}`} className="block rounded-lg bg-white/70 p-3 text-xs font-bold text-orange-900">{r.reference} · {r.reason}</SafeLink>)}</div></section>}</aside>
    </div>
  </div>;
}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3"><span className="text-slate-500">{label}</span><strong className="max-w-[65%] break-words text-right text-slate-800">{value}</strong></div>}
