"use client";
import { reports } from "@/data/mock-data";
import { PageHeader } from "@/components/ui/page-header";
import { DataTable } from "@/components/ui/data-table";
import { StatusBadge } from "@/components/ui/status-badge";
import { SafeLink } from "@/components/ui/safe-link";
import { Icons } from "@/lib/icons";
import { useAdminDemo } from "@/components/admin/admin-demo-provider";
export default function ReportsPage(){const {getStatus}=useAdminDemo();return <div className="space-y-6"><PageHeader title="Reports" description="Investigate user-submitted safety and marketplace policy reports."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Open","31","Needs triage"],["High priority","9","Review first"],["Under review","14","Assigned"],["Resolved today","42","Median 18m"]].map(([a,b,c])=><div key={a} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">{a}</p><strong className="mt-2 block text-xl font-black">{b}</strong><p className="mt-1 text-[10px] text-slate-400">{c}</p></div>)}</div><DataTable rows={reports} searchText={r=>`${r.id} ${r.target} ${r.type} ${r.reason} ${r.reporter} ${r.priority}`} searchPlaceholder="Search target, reporter or report ID…" statusOf={r=>getStatus("report",r.id,r.status)} statuses={["Open","Review","Resolved","Dismissed"]} selectedLabel="reports" columns={[
{key:"report",label:"Report",cell:r=><div><div className="max-w-[260px] truncate font-bold text-slate-900">{r.target}</div><div className="mt-0.5 text-[10px] text-slate-400">{r.id} · {r.type}</div></div>},{key:"reason",label:"Reason",cell:r=>r.reason},{key:"reporter",label:"Reporter",cell:r=>r.reporter},{key:"priority",label:"Priority",cell:r=><span className={`font-black ${r.priority==="High"?"text-red-600":r.priority==="Medium"?"text-amber-600":"text-slate-500"}`}>{r.priority}</span>},{key:"created",label:"Created",cell:r=>r.created},{key:"status",label:"Status",cell:r=><StatusBadge status={getStatus("report",r.id,r.status)}/>},{key:"action",label:"",cell:r=><SafeLink href={`/reports/${r.id}`} aria-label={`Review report ${r.id}`} className="grid size-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><Icons.chevronRight size={16}/></SafeLink>}]}/></div>}
