"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { SafeLink } from "@/components/ui/safe-link";
import { AdminButton } from "@/components/ui/admin-button";
import { StatusBadge } from "@/components/ui/status-badge";
import { graphqlRequest } from "@/lib/api-client";
import { useAdminData } from "@/components/admin/admin-data-provider";
import type { Status } from "@/types/admin";

type Message={id:string;senderName:string|null;body:string;internal:boolean;attachmentUrl:string|null;createdAt:string};
type Ticket={id:string;reference:string;userId:string;userName:string;subject:string;category:string;priority:string;status:string;assignedTo:string|null;updatedAt:string;createdAt:string;messages:Message[]};
type Staff={id:string;name:string;email:string;active:boolean;suspended:boolean;adminRole:string|null};
const QUERY=`query SupportTicket($id:ID!){supportTicket(id:$id){id reference userId userName subject category priority status assignedTo updatedAt createdAt messages{id senderName body internal attachmentUrl createdAt}}}`;
const STAFF_QUERY=`query SupportAssignees { adminStaff(limit:100){id name email active suspended adminRole} }`;
const fmt=(v:string)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const title=(v:string)=>v.replace(/_/g," ").replace(/\b\w/g,(c)=>c.toUpperCase());
const statusUi=(v:string):Status=>(v==="review"?"Review":title(v)) as Status;

export default function SupportTicketPage(){
  const {ticketId}=useParams<{ticketId:string}>(); const {toast,canAccess,sessionUser}=useAdminData();
  const [ticket,setTicket]=useState<Ticket|null>(null); const [staff,setStaff]=useState<Staff[]>([]); const [loading,setLoading]=useState(true); const [message,setMessage]=useState(""); const [internal,setInternal]=useState(false); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const d=await graphqlRequest<{supportTicket:Ticket|null}>(QUERY,{id:ticketId});setTicket(d.supportTicket);if(canAccess("settings")){const a=await graphqlRequest<{adminStaff:Staff[]}>(STAFF_QUERY);setStaff(a.adminStaff.filter((x)=>x.active&&!x.suspended));}}catch(e){toast("Ticket unavailable",e instanceof Error?e.message:undefined,"danger");}finally{setLoading(false)}},[ticketId,canAccess,toast]);
  useEffect(()=>{const timeoutId=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timeoutId)},[load]);
  async function updateWorkflow(input:{status?:string;priority?:string;assignedToUserId?:string}){if(!ticket)return;try{const d=await graphqlRequest<{adminUpdateSupportTicket:Ticket}>(`mutation($id:ID!,$status:String,$priority:String,$assignedToUserId:ID){adminUpdateSupportTicket(ticketId:$id,status:$status,priority:$priority,assignedToUserId:$assignedToUserId){id reference userId userName subject category priority status assignedTo updatedAt createdAt messages{id senderName body internal attachmentUrl createdAt}}}`,{id:ticket.id,...input});setTicket(d.adminUpdateSupportTicket);toast("Ticket updated");}catch(e){toast("Ticket update failed",e instanceof Error?e.message:undefined,"danger");}}
  async function send(){if(!ticket||message.trim().length<2)return;setBusy(true);try{const d=await graphqlRequest<{adminReplySupportTicket:Ticket}>(`mutation($id:ID!,$message:String!,$internal:Boolean!){adminReplySupportTicket(ticketId:$id,message:$message,internal:$internal,status:"review"){id reference userId userName subject category priority status assignedTo updatedAt createdAt messages{id senderName body internal attachmentUrl createdAt}}}`,{id:ticket.id,message:message.trim(),internal});setTicket(d.adminReplySupportTicket);setMessage("");toast(internal?"Internal note added":"Reply sent");}catch(e){toast("Message could not be saved",e instanceof Error?e.message:undefined,"danger");}finally{setBusy(false)}}
  if(loading)return <div className="rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Loading support ticket…</div>;
  if(!ticket)return <div className="rounded-xl border border-slate-200 bg-white p-8 text-center"><h1 className="text-lg font-black">Support ticket not found</h1><SafeLink href="/support" className="mt-4 inline-flex text-sm font-bold text-emerald-700">Back to support</SafeLink></div>;
  return <div className="space-y-6"><SafeLink href="/support" className="text-xs font-bold text-slate-500">← Back to support</SafeLink>
    <div className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-xl font-black">{ticket.subject}</h1><StatusBadge status={statusUi(ticket.status)}/></div><p className="mt-1 text-xs text-slate-500">{ticket.reference} · {ticket.userName} · created {fmt(ticket.createdAt)}</p></div><div className="flex flex-wrap gap-2"><select aria-label="Ticket priority" value={ticket.priority} onChange={(e)=>void updateWorkflow({priority:e.target.value})} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-bold"><option value="low">Low priority</option><option value="medium">Medium priority</option><option value="high">High priority</option><option value="urgent">Urgent priority</option></select><select aria-label="Ticket status" value={ticket.status} onChange={(e)=>void updateWorkflow({status:e.target.value})} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-bold"><option value="open">Open</option><option value="review">In review</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></div></div>
    <div className="grid gap-6 xl:grid-cols-[1fr_320px]"><section className="rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="text-sm font-black">Conversation</h2><p className="mt-0.5 text-xs text-slate-500">Customer messages, administrator replies and internal notes</p></div><div className="max-h-[620px] space-y-4 overflow-y-auto p-5">{ticket.messages.map((item)=><article key={item.id} className={`rounded-xl border p-4 ${item.internal?"border-amber-200 bg-amber-50/50":"border-slate-200 bg-slate-50/60"}`}><div className="flex items-center justify-between gap-3"><strong className="text-xs text-slate-900">{item.senderName||"Marketlift"}{item.internal&&<span className="ml-2 rounded-full bg-amber-100 px-2 py-0.5 text-[9px] text-amber-800">Internal</span>}</strong><span className="text-[10px] text-slate-400">{fmt(item.createdAt)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{item.body}</p>{item.attachmentUrl&&<a href={item.attachmentUrl} target="_blank" rel="noreferrer" className="mt-3 inline-flex text-xs font-bold text-emerald-700">Open attachment</a>}</article>)}{ticket.messages.length===0&&<p className="text-sm text-slate-500">No messages have been recorded.</p>}</div><div className="border-t border-slate-100 p-5"><label className="block"><span className="mb-2 block text-xs font-bold text-slate-700">{internal?"Internal note":"Reply to customer"}</span><textarea value={message} onChange={(e)=>setMessage(e.target.value)} className="min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10" placeholder={internal?"Add information only administrators should see…":"Write a clear response to the customer…"}/></label><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={internal} onChange={(e)=>setInternal(e.target.checked)}/> Internal note</label><AdminButton disabled={busy||message.trim().length<2} onClick={()=>void send()}>{busy?"Saving…":internal?"Add note":"Send reply"}</AdminButton></div></div></section>
      <aside className="space-y-5"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Ticket details</h2><dl className="mt-4 space-y-4 text-xs"><Row label="Customer" value={ticket.userName}/><Row label="Category" value={title(ticket.category)}/><Row label="Priority" value={title(ticket.priority)}/><Row label="Updated" value={fmt(ticket.updatedAt)}/><Row label="Assigned to" value={ticket.assignedTo||"Unassigned"}/></dl></section><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Assignment</h2><p className="mt-1 text-xs text-slate-500">Assign this ticket to an active administrator.</p>{canAccess("settings")?<select aria-label="Assign support ticket" defaultValue="" onChange={(e)=>{if(e.target.value)void updateWorkflow({assignedToUserId:e.target.value})}} className="mt-4 h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs"><option value="">Choose administrator…</option>{staff.map((item)=><option key={item.id} value={item.id}>{item.name} · {(item.adminRole||"admin").replace(/_/g," ")}</option>)}</select>:<AdminButton variant="outline" className="mt-4 w-full" onClick={()=>sessionUser&&void updateWorkflow({assignedToUserId:sessionUser.id})}>Assign to me</AdminButton>}</section></aside>
    </div>
  </div>;
}
function Row({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3"><dt className="text-slate-500">{label}</dt><dd className="max-w-[65%] text-right font-bold text-slate-800">{value}</dd></div>}
