"use client";
import { SafeLink } from "@/components/ui/safe-link";
import { KpiCard } from "@/components/ui/kpi-card";
import { StatusBadge } from "@/components/ui/status-badge";
import { PageHeader } from "@/components/ui/page-header";
import { useAdminData } from "@/components/admin/admin-data-provider";
import { Icons } from "@/lib/icons";
import { DashboardActivityCard } from "@/components/admin/dashboard-activity-card";
import { MarketplaceImage } from "@/components/admin/marketplace-image";
import type { AdminArea } from "@/lib/admin-access";
import { releaseFeatures } from "@/lib/release-features";

const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value).replace(/\u00a0/g," ");

export default function DashboardPage() {
  const {activityLog,listings,dashboard,sessionUser,canAccess}=useAdminData(); const {counts,revenue}=dashboard;
  const stats=[
    {label:"Total users",value:counts.totalUsers.toLocaleString("pt-BR"),change:`${counts.totalSellers} sellers`,trend:"up" as const,meta:"Registered accounts"},
    {label:"Published listings",value:counts.publishedListings.toLocaleString("pt-BR"),change:`${counts.totalListings} total`,trend:"up" as const,meta:"Marketplace catalog"},
    ...(releaseFeatures.payments?[{label:"Revenue this month",value:money(revenue.thisMonth),change:money(revenue.today),trend:"up" as const,meta:"Today"},{label:"Recorded payments",value:counts.recordedPayments.toLocaleString("pt-BR"),change:`${counts.failedPayments} failed`,trend:counts.failedPayments?"down" as const:"up" as const,meta:"Seller billing"}]:[{label:"Active sellers",value:counts.activeSellers.toLocaleString("pt-BR"),change:`${counts.totalSellers} total`,trend:"up" as const,meta:"Marketplace sellers"},{label:"Open support",value:counts.openSupportTickets.toLocaleString("pt-BR"),change:"Needs attention",trend:counts.openSupportTickets?"down" as const:"up" as const,meta:"Support queue"}]),
  ];
  const attention:{label:string;count:number;href:string;tone:string;area:AdminArea}[]=[
    {label:"Verification requests",count:counts.pendingVerifications,href:"/verifications",tone:"amber",area:"verifications"},
    {label:"Listings under review",count:counts.listingsUnderReview,href:"/moderation",tone:"red",area:"moderation"},
    {label:"Open reports",count:counts.openReports,href:"/reports",tone:"orange",area:"reports"},
    {label:"Failed payments",count:counts.failedPayments,href:"/payments",tone:"red",area:"payments"},
    {label:"Support tickets",count:counts.openSupportTickets,href:"/support",tone:"blue",area:"support"},
    {label:"Reported listings",count:counts.reportedListings,href:"/listings",tone:"amber",area:"listings"},
  ];
  const visibleAttention=attention.filter((item)=>canAccess(item.area)&&(item.area!=="payments"||releaseFeatures.payments)&&(item.area!=="verifications"||releaseFeatures.cpfVerification)); const attentionTotal=visibleAttention.reduce((sum,item)=>sum+item.count,0);
  const listingStatus=[["Published",counts.publishedListings,"bg-emerald-500"],["Under review",counts.listingsUnderReview,"bg-blue-500"],["Rejected",counts.rejectedListings,"bg-red-500"],["Reported",counts.reportedListings,"bg-orange-500"]] as const;
  const listingTotal=Math.max(counts.totalListings,1);
  return <div className="space-y-6">
    <PageHeader title={`Welcome, ${sessionUser?.name?.split(" ")[0]||"Admin"}`} description="Here’s what’s happening on Marketlift today."/>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map((stat)=><KpiCard key={stat.label} {...stat}/>)}</section>
    {visibleAttention.length>0&&<section className="rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,.03)]"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-sm font-black text-slate-900">Action required</h2><p className="mt-0.5 text-xs text-slate-500">Queues available to your administrator role</p></div><span className="rounded-full bg-red-50 px-2 py-1 text-[10px] font-black text-red-600">{attentionTotal} total</span></div><div className="grid sm:grid-cols-2 xl:grid-cols-3">{visibleAttention.map((item,index)=><SafeLink key={item.label} href={item.href} className={`flex items-center gap-3 border-slate-100 p-4 transition hover:bg-slate-50 ${index<3?"xl:border-b":""} ${index%3!==2?"xl:border-r":""}`}><span className={`grid size-9 place-items-center rounded-lg ${item.tone==="red"?"bg-red-50 text-red-600":item.tone==="blue"?"bg-blue-50 text-blue-600":item.tone==="orange"?"bg-orange-50 text-orange-600":"bg-amber-50 text-amber-600"}`}><Icons.alert size={17}/></span><span className="min-w-0 flex-1"><span className="block text-xs font-bold text-slate-800">{item.label}</span><span className="text-[11px] text-slate-400">Review queue</span></span><strong className="text-base font-black text-slate-950">{item.count}</strong><Icons.chevronRight size={15} className="text-slate-300"/></SafeLink>)}</div></section>}
    <section className="grid gap-6 xl:grid-cols-[1.65fr_.85fr]">{canAccess("activity")?<DashboardActivityCard/>:releaseFeatures.payments?<div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Revenue summary</h2><div className="mt-5 grid grid-cols-2 gap-3">{[["Today",revenue.today],["This month",revenue.thisMonth],["Subscriptions",revenue.subscriptionTotal],["Promotions",revenue.promotionTotal]].map(([label,value])=><div key={String(label)} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase text-slate-400">{label}</p><strong className="mt-2 block text-sm font-black">{money(Number(value))}</strong></div>)}</div></div>:<div className="rounded-xl border border-amber-200 bg-amber-50/50 p-5"><h2 className="text-sm font-black text-amber-950">Payments upcoming</h2><p className="mt-2 text-xs leading-5 text-amber-900/75">Revenue, subscription and promotion controls stay dormant until provider certification.</p></div>}<div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black text-slate-900">Listing status</h2><p className="mt-0.5 text-xs text-slate-500">Current marketplace catalog</p><div className="mt-6 space-y-5">{listingStatus.map(([label,count,color])=><div key={label}><div className="mb-1.5 flex justify-between text-xs"><span className="font-semibold text-slate-600">{label}</span><strong className="text-slate-900">{count.toLocaleString("pt-BR")}</strong></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{width:`${Math.max(count?6:0,Math.round(count/listingTotal*100))}%`}}/></div></div>)}</div></div></section>
    <section className="grid gap-6 xl:grid-cols-[1.5fr_1fr]">
      {canAccess("listings")&&<div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between px-5 py-4"><div><h2 className="text-sm font-black text-slate-900">Recent listings</h2><p className="mt-0.5 text-xs text-slate-500">Latest loaded catalog items</p></div><SafeLink href="/listings" className="text-xs font-black text-emerald-700">View all</SafeLink></div><div className="table-scroll"><table className="admin-table"><thead><tr><th>Listing</th><th>Seller</th><th>Price</th><th>Status</th><th/></tr></thead><tbody>{listings.slice(0,5).map((item)=><tr key={item.id}><td><div className="flex items-center gap-3"><MarketplaceImage src={item.image} alt={`${item.title} thumbnail`} className="size-10 shrink-0 rounded-lg object-cover" fallbackClassName="size-10 shrink-0 rounded-lg"/><div><div className="font-bold text-slate-900">{item.title}</div><div className="mt-0.5 text-[10px] text-slate-400">{item.id} · {item.category}</div></div></div></td><td>{item.seller}</td><td className="font-semibold text-slate-700">{item.price}</td><td><StatusBadge status={item.status}/></td><td><SafeLink href={`/listings/${item.id}`} className="text-xs font-bold text-emerald-700">View</SafeLink></td></tr>)}</tbody></table></div></div>}
      {canAccess("activity")&&<div className="rounded-xl border border-slate-200 bg-white"><div className="px-5 py-4"><h2 className="text-sm font-black text-slate-900">Recent admin activity</h2><p className="mt-0.5 text-xs text-slate-500">Latest operational actions</p></div><div className="px-5 pb-3">{activityLog.slice(0,5).map((item,index)=><div key={item.id} className="relative flex gap-3 pb-5 last:pb-2"><div className="relative z-10 grid size-8 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-500"><Icons.activity size={14}/></div>{index<4&&<div className="absolute left-[15px] top-8 h-[calc(100%-22px)] w-px bg-slate-100"/>}<div className="min-w-0 pt-0.5"><p className="text-xs leading-5 text-slate-600"><strong className="text-slate-800">{item.admin}</strong> {item.action.toLowerCase()}</p><p className="truncate text-[10px] text-slate-400">{item.target}</p><p className="mt-0.5 text-[10px] text-slate-400">{item.time}</p></div></div>)}</div></div>}
    </section>
  </div>;
}
