"use client";
import { sellers } from "@/data/mock-data";
import { PageHeader } from "@/components/ui/page-header";
import { DataTable } from "@/components/ui/data-table";
import { StatusBadge } from "@/components/ui/status-badge";
import { AdminButton } from "@/components/ui/admin-button";
import { SafeLink } from "@/components/ui/safe-link";
import { Icons } from "@/lib/icons";
import { useAdminDemo } from "@/components/admin/admin-demo-provider";

export default function SellersPage(){const {getStatus,toast}=useAdminDemo();return <div className="space-y-6"><PageHeader title="Sellers" description="Monitor seller health, plans, inventory and marketplace standing." actions={<AdminButton variant="outline" onClick={()=>toast("Seller export prepared",undefined,"info")}><Icons.download size={16}/> Export</AdminButton>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total sellers","4,281","+5.2%"],["Verified","4,109","96.0%"],["Pending review","18","Needs attention"],["Paid plans","2,097","49.0%"]].map(([a,b,c])=><div key={a} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">{a}</p><strong className="mt-2 block text-xl font-black">{b}</strong><p className="mt-1 text-[10px] text-slate-400">{c}</p></div>)}</div><DataTable rows={sellers} searchText={(s)=>`${s.id} ${s.name} ${s.owner} ${s.plan} ${s.location}`} searchPlaceholder="Search seller, owner or seller ID…" statusOf={(s)=>getStatus("seller",s.id,s.status)} statuses={["Verified","Pending","Suspended"]} selectedLabel="sellers" columns={[
{key:"seller",label:"Seller",cell:s=><div><div className="font-bold text-slate-900">{s.name}</div><div className="mt-0.5 text-[10px] text-slate-400">{s.id} · {s.owner}</div></div>},{key:"plan",label:"Plan",cell:s=><span className="font-bold text-slate-700">{s.plan}</span>},{key:"location",label:"Location",cell:s=>s.location},{key:"listings",label:"Listings",cell:s=>s.listings.toLocaleString("pt-BR")},{key:"rating",label:"Rating",cell:s=><span className="font-bold text-slate-700">★ {s.rating}</span>},{key:"status",label:"Status",cell:s=><StatusBadge status={getStatus("seller",s.id,s.status)}/>},{key:"action",label:"",cell:s=><SafeLink href={`/sellers/${s.id}`} aria-label={`View seller ${s.name}`} className="grid size-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><Icons.chevronRight size={16}/></SafeLink>}]}/></div>}
