"use client";
import { payments } from "@/data/mock-data";
import { PageHeader } from "@/components/ui/page-header";
import { DataTable } from "@/components/ui/data-table";
import { StatusBadge } from "@/components/ui/status-badge";
import { AdminButton } from "@/components/ui/admin-button";
import { Icons } from "@/lib/icons";
import { useAdminDemo } from "@/components/admin/admin-demo-provider";
export default function PaymentsPage(){const {toast}=useAdminDemo();return <div className="space-y-6"><PageHeader title="Payments" description="Monitor Marketlift subscription and promotion transactions." actions={<AdminButton variant="outline" onClick={()=>toast("Payment export prepared",undefined,"info")}><Icons.download size={16}/> Export</AdminButton>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Gross volume","R$ 92,7k","+7.1%"],["Net revenue","R$ 84,3k","+6.1%"],["Success rate","97.4%","Healthy"],["Failed today","6","Needs review"]].map(([a,b,c])=><div key={a} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">{a}</p><strong className="mt-2 block text-xl font-black">{b}</strong><p className="mt-1 text-[10px] text-slate-400">{c}</p></div>)}</div><DataTable rows={payments} searchText={p=>`${p.id} ${p.seller} ${p.type} ${p.method} ${p.status}`} searchPlaceholder="Search payment, seller or transaction ID…" statusOf={p=>p.status} statuses={["Paid","Failed","Refunded"]} selectedLabel="payments" columns={[
{key:"payment",label:"Payment",cell:p=><div><div className="font-bold text-slate-900">{p.id}</div><div className="mt-0.5 text-[10px] text-slate-400">{p.seller}</div></div>},{key:"type",label:"Product",cell:p=>p.type},{key:"amount",label:"Amount",cell:p=><strong className="text-slate-800">{p.amount}</strong>},{key:"method",label:"Method",cell:p=>p.method},{key:"date",label:"Date",cell:p=>p.date},{key:"status",label:"Status",cell:p=><StatusBadge status={p.status}/>},{key:"action",label:"",cell:p=><button type="button" aria-label={`View payment ${p.id}`} onClick={()=>toast(`Opened ${p.id}`,"Transaction details opened.","info")} className="grid size-8 place-items-center rounded-lg text-slate-500 hover:bg-slate-100"><Icons.eye size={16}/></button>}]}/></div>}
