"use client";

import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { SafeLink } from "@/components/ui/safe-link";
import { LiveStatusBadge } from "@/components/ui/live-status-badge";
import { EntityActions } from "@/components/admin/entity-actions";
import { AdminButton } from "@/components/ui/admin-button";
import { graphqlRequest } from "@/lib/api-client";
import { useAdminData } from "@/components/admin/admin-data-provider";
import type { Status } from "@/types/admin";

type Report={id:string;reference:string;targetType:string;targetId:string;targetLabel:string;reason:string;statement:string;priority:string;status:string;reporterName:string|null;assignedTo:string|null;internalNote:string|null;decisionReason:string|null;createdAt:string;decidedAt:string|null};
const QUERY=`query AdminReportDetail($id:String!){report(id:$id){id reference targetType targetId targetLabel reason statement priority status reporterName assignedTo internalNote decisionReason createdAt decidedAt}}`;
const title=(v?:string|null)=>v?v.replace(/_/g," ").replace(/\b\w/g,(c)=>c.toUpperCase()):"—";
const fmt=(v:string)=>new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v));
const uiStatus=(v:string):Status=>({open:"Open",review:"Review",resolved:"Resolved",dismissed:"Dismissed"}[v]||title(v)) as Status;

export default function ReportDetailPage(){
  const {reportId}=useParams<{reportId:string}>(); const {toast,setStatus}=useAdminData(); const [report,setReport]=useState<Report|null>(null); const [loading,setLoading]=useState(true); const [note,setNote]=useState(""); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const d=await graphqlRequest<{report:Report|null}>(QUERY,{id:reportId});setReport(d.report);setNote(d.report?.internalNote||"");}catch(e){toast("Report unavailable",e instanceof Error?e.message:undefined,"danger");}finally{setLoading(false)}},[reportId,toast]);
  useEffect(()=>{const timeoutId=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timeoutId)},[load]);
  async function saveNote(){if(!report||note.trim().length<2)return;setSaving(true);try{await graphqlRequest(`mutation($id:ID!,$note:String!){saveReportNote(reportId:$id,note:$note){id internalNote}}`,{id:report.id,note:note.trim()});toast("Internal note saved");await load();}catch(e){toast("Note could not be saved",e instanceof Error?e.message:undefined,"danger");}finally{setSaving(false)}}
  if(loading)return <div className="rounded-xl border bg-white p-8 text-sm text-slate-500">Loading report…</div>;
  if(!report)return <div className="rounded-xl border bg-white p-8 text-center"><h1 className="text-lg font-black">Report not found</h1><SafeLink href="/reports" className="mt-4 inline-flex text-sm font-bold text-emerald-700">Back to reports</SafeLink></div>;
  const status=uiStatus(report.status);
  return <div className="space-y-6"><SafeLink href="/reports" className="text-xs font-bold text-slate-500">← Back to reports</SafeLink>
    <div className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-xl font-black">{report.reference}</h1><LiveStatusBadge kind="report" id={report.id} status={status}/></div><p className="mt-1 text-xs text-slate-500">{title(report.reason)} · {fmt(report.createdAt)}</p></div><div className="flex flex-wrap gap-2">{status==="Open"&&<AdminButton variant="outline" onClick={()=>void setStatus("report",report.id,"Review","Report moved to review","Investigation started").then(load)}>Move to review</AdminButton>}<EntityActions kind="report" id={report.id} name={report.targetLabel||report.targetId} status={status}/></div></div>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><section className="space-y-6"><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Report details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Row label="Target type" value={title(report.targetType)}/><Row label="Target" value={report.targetLabel||report.targetId}/><Row label="Reporter" value={report.reporterName||"—"}/><Row label="Priority" value={title(report.priority)}/><Row label="Reason" value={title(report.reason)}/><Row label="Assigned to" value={report.assignedTo||"—"}/><Row label="Decision time" value={report.decidedAt?fmt(report.decidedAt):"—"}/></div>{report.statement&&<div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Reporter statement</p><p className="mt-2 text-sm leading-6 text-slate-700">{report.statement}</p></div>}{report.internalNote&&<div className="mt-4 rounded-xl border border-blue-100 bg-blue-50/50 p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-blue-500">Internal note</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-blue-950">{report.internalNote}</p></div>}{report.decisionReason&&<div className="mt-4 rounded-xl border border-slate-200 p-4"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Decision reason</p><p className="mt-2 text-sm leading-6 text-slate-700">{report.decisionReason}</p></div>}</div>
      <div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Internal investigation note</h2><p className="mt-1 text-xs text-slate-500">Visible only to administrators handling reports.</p><textarea value={note} onChange={(e)=>setNote(e.target.value)} className="mt-4 min-h-28 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/10" placeholder="Add investigation context, evidence references or handoff notes…"/><div className="mt-3 flex justify-end"><AdminButton disabled={saving||note.trim().length<2} onClick={()=>void saveNote()}>{saving?"Saving…":"Save note"}</AdminButton></div></div></section>
      <aside className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Reported target</h2><p className="mt-2 text-xs leading-5 text-slate-500">{report.targetLabel||report.targetId}</p><div className="mt-4">{["listing","seller","user"].includes(report.targetType)?<SafeLink href={`/${report.targetType==="listing"?"listings":report.targetType==="seller"?"sellers":"users"}/${report.targetId}`} className="inline-flex min-h-10 items-center rounded-lg border border-slate-300 px-3.5 text-sm font-bold text-emerald-700 hover:bg-slate-50">Open {title(report.targetType)} record</SafeLink>:<span className="text-xs text-slate-500">Target ID: {report.targetId}</span>}</div></section><section className="rounded-xl border border-amber-200 bg-amber-50/40 p-5"><h2 className="text-sm font-black text-amber-950">Investigation guidance</h2><p className="mt-2 text-xs leading-5 text-amber-900/75">Review the submitted statement and the reported target before recording a final decision.</p></section></aside>
    </div>
  </div>;
}
function Row({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-xs font-semibold text-slate-800">{value||"—"}</p></div>}
