"use client";
import { useParams } from "next/navigation";
import { SafeLink } from "@/components/ui/safe-link";
import { LiveStatusBadge } from "@/components/ui/live-status-badge";
import { EntityActions } from "@/components/admin/entity-actions";
import { MarketplaceImage } from "@/components/admin/marketplace-image";
import { useAdminData } from "@/components/admin/admin-data-provider";
export default function VerificationDetailPage(){const {verificationId}=useParams<{verificationId:string}>();const {verifications,loading}=useAdminData();const v=verifications.find((x)=>x.id===verificationId);if(loading&&!v)return <div className="rounded-xl border bg-white p-8 text-sm text-slate-500">Loading verification…</div>;if(!v)return <div className="rounded-xl border bg-white p-8 text-center"><h1 className="text-lg font-black">Verification not found</h1><SafeLink href="/verifications" className="mt-4 inline-flex text-sm font-bold text-emerald-700">Back to verifications</SafeLink></div>;return <div className="space-y-6"><SafeLink href="/verifications" className="text-xs font-bold text-slate-500">← Back to verifications</SafeLink><div className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><h1 className="text-xl font-black">{v.seller}</h1><LiveStatusBadge kind="verification" id={v.id} status={v.status}/></div><p className="mt-1 text-xs text-slate-500">{v.id} · submitted {v.submitted}</p></div><EntityActions kind="verification" id={v.id} name={v.seller} status={v.status}/></div><div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="text-sm font-black">Identity information</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Row label="Legal name" value={v.legalName}/><Row label="CPF" value={v.cpfMasked}/><Row label="Date of birth" value={v.birthDate}/><Row label="Document" value={v.document}/><Row label="Risk level" value={v.risk}/><Row label="Seller ID" value={v.sellerId}/></div>{v.flags.length>0&&<div className="mt-5"><p className="text-[10px] font-bold uppercase text-slate-400">Risk flags</p><div className="mt-2 flex flex-wrap gap-2">{v.flags.map((flag)=><span key={flag} className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-800">{flag}</span>)}</div></div>}{v.decisionNote&&<div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase text-slate-400">Decision note</p><p className="mt-2 text-sm text-slate-700">{v.decisionNote}</p></div>}</section><aside className="space-y-5"><Media label="Document front" src={v.documentFrontUrl}/><Media label="Document back" src={v.documentBackUrl}/><Media label="Selfie" src={v.selfieUrl}/></aside></div></div>}
function Row({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 break-words text-xs font-semibold text-slate-800">{value||"—"}</p></div>}
function Media({label,src}:{label:string;src:string}){return <section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-xs font-black text-slate-700">{label}</h2>{src?<MarketplaceImage src={src} alt={label} className="mt-3 max-h-72 w-full rounded-lg object-contain" fallbackClassName="mt-3 h-40 w-full rounded-lg"/>:<p className="mt-3 text-xs text-slate-500">Not provided</p>}</section>}
