// AUTO-GENERATED from the sibling Marketlift marketplace frontend.
// Do not edit this file manually. Re-run the domain sync patch while the frontend is mock-backed.
// When the Django API is connected, these shapes become API responses instead of source-code snapshots.

export const marketplaceDomain = {
  "categories": [
    {
      "id": "phones",
      "name": "Mobile Phones",
      "slug": "phones",
      "icon": "📱",
      "active": true,
      "subcategories": []
    },
    {
      "id": "electronics",
      "name": "Electronics",
      "slug": "electronics",
      "icon": "Tv",
      "active": true,
      "subcategories": []
    },
    {
      "id": "computers",
      "name": "Computers",
      "slug": "computers",
      "icon": "Laptop",
      "active": true,
      "subcategories": []
    },
    {
      "id": "vehicles",
      "name": "Vehicles",
      "slug": "vehicles",
      "icon": "Car",
      "active": true,
      "subcategories": []
    },
    {
      "id": "properties",
      "name": "Properties",
      "slug": "properties",
      "icon": "📦",
      "active": true,
      "subcategories": []
    },
    {
      "id": "land",
      "name": "Land",
      "slug": "land",
      "icon": "Map",
      "active": true,
      "subcategories": []
    },
    {
      "id": "home",
      "name": "Home & Garden",
      "slug": "home",
      "icon": "Sofa",
      "active": true,
      "subcategories": []
    },
    {
      "id": "fashion",
      "name": "Fashion",
      "slug": "fashion",
      "icon": "Shirt",
      "active": true,
      "subcategories": []
    },
    {
      "id": "services",
      "name": "Services",
      "slug": "services",
      "icon": "Wrench",
      "active": true,
      "subcategories": []
    },
    {
      "id": "jobs",
      "name": "Jobs",
      "slug": "jobs",
      "icon": "🧰",
      "active": true,
      "subcategories": []
    },
    {
      "id": "agriculture",
      "name": "Agriculture",
      "slug": "agriculture",
      "icon": "Tractor",
      "active": true,
      "subcategories": []
    },
    {
      "id": "business",
      "name": "Business",
      "slug": "business",
      "icon": "Store",
      "active": true,
      "subcategories": []
    },
    {
      "id": "other",
      "name": "Other",
      "slug": "other",
      "icon": "Grid3X3",
      "active": true,
      "subcategories": []
    }
  ],
  "listings": [
    {
      "id": "12345",
      "slug": "honda-civic-2018-12345",
      "title": "Honda Civic EXL 2018 Automatic",
      "sellerId": "seller-1",
      "sellerName": "AutoPrime SP",
      "categoryId": "vehicles",
      "categoryName": "Vehicles",
      "price": 89000,
      "images": [
        "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=85",
        "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1200&q=85",
        "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1200&q=85"
      ],
      "description": "Well maintained Civic with complete service history, leather interior and recently serviced transmission. Documentation ready for transfer.",
      "condition": "Used",
      "location": "São Paulo, SP",
      "status": "Active"
    },
    {
      "id": "12346",
      "slug": "iphone-15-pro-256gb-12346",
      "title": "iPhone 15 Pro 256GB Titanium",
      "sellerId": "seller-3",
      "sellerName": "Tech House Campinas",
      "categoryId": "phones",
      "categoryName": "Mobile Phones",
      "price": 5790,
      "images": [
        "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Excellent condition, battery health 96%, original box and cable included.",
      "condition": "Like new",
      "location": "Campinas, SP",
      "status": "Active"
    },
    {
      "id": "12347",
      "slug": "apartment-vila-mariana-12347",
      "title": "2 Bedroom Apartment in Vila Mariana",
      "sellerId": "seller-2",
      "sellerName": "Mariana Costa",
      "categoryId": "properties",
      "categoryName": "Properties",
      "price": 695000,
      "images": [
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Bright apartment near metro, 2 bedrooms, balcony, parking and 24h security.",
      "condition": "Used",
      "location": "São Paulo, SP",
      "status": "Active"
    },
    {
      "id": "12348",
      "slug": "samsung-galaxy-s24-12348",
      "title": "Samsung Galaxy S24 256GB",
      "sellerId": "seller-2",
      "sellerName": "Mariana Costa",
      "categoryId": "phones",
      "categoryName": "Mobile Phones",
      "price": 3490,
      "images": [
        "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Unlocked S24, lightly used with case and screen protector from day one.",
      "condition": "Like new",
      "location": "Rio de Janeiro, RJ",
      "status": "Active"
    },
    {
      "id": "12349",
      "slug": "dell-inspiron-15-12349",
      "title": "Dell Inspiron 15 Ryzen 7 Laptop",
      "sellerId": "seller-3",
      "sellerName": "Tech House Campinas",
      "categoryId": "computers",
      "categoryName": "Computers",
      "price": 3190,
      "images": [
        "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Fast everyday notebook with 16GB RAM and 512GB SSD. Great for work and study.",
      "condition": "Used",
      "location": "Belo Horizonte, MG",
      "status": "Active"
    },
    {
      "id": "12350",
      "slug": "toyota-corolla-2021-12350",
      "title": "Toyota Corolla Altis 2021",
      "sellerId": "seller-1",
      "sellerName": "AutoPrime SP",
      "categoryId": "vehicles",
      "categoryName": "Vehicles",
      "price": 128900,
      "images": [
        "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Single owner, low mileage, full dealership history.",
      "condition": "Used",
      "location": "Curitiba, PR",
      "status": "Active"
    },
    {
      "id": "12351",
      "slug": "macbook-air-m2-12351",
      "title": "MacBook Air M2 13-inch 256GB",
      "sellerId": "seller-3",
      "sellerName": "Tech House Campinas",
      "categoryId": "computers",
      "categoryName": "Computers",
      "price": 6490,
      "images": [
        "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Space gray MacBook Air with low battery cycle count and original charger.",
      "condition": "Like new",
      "location": "São Paulo, SP",
      "status": "Active"
    },
    {
      "id": "12352",
      "slug": "sofa-three-seater-12352",
      "title": "Modern 3-Seater Sofa in Excellent Condition",
      "sellerId": "seller-4",
      "sellerName": "Casa Viva Curitiba",
      "categoryId": "home",
      "categoryName": "Home & Garden",
      "price": 1850,
      "images": [
        "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Comfortable neutral sofa, lightly used and ideal for apartment living.",
      "condition": "Used",
      "location": "São Paulo, SP",
      "status": "Active"
    },
    {
      "id": "12353",
      "slug": "lg-air-conditioner-12353",
      "title": "LG Dual Inverter Air Conditioner 12000 BTU",
      "sellerId": "seller-2",
      "sellerName": "Mariana Costa",
      "categoryId": "electronics",
      "categoryName": "Electronics",
      "price": 2250,
      "images": [
        "https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Energy-efficient split air conditioner, working perfectly with remote included.",
      "condition": "Used",
      "location": "Rio de Janeiro, RJ",
      "status": "Active"
    },
    {
      "id": "12354",
      "slug": "house-campinas-12354",
      "title": "Family House with 3 Bedrooms in Campinas",
      "sellerId": "seller-2",
      "sellerName": "Mariana Costa",
      "categoryId": "properties",
      "categoryName": "Properties",
      "price": 780000,
      "images": [
        "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Spacious home with backyard, covered parking and easy access to local services.",
      "condition": "Used",
      "location": "Campinas, SP",
      "status": "Active"
    },
    {
      "id": "12355",
      "slug": "yamaha-fazer-250-12355",
      "title": "Yamaha Fazer 250 2023",
      "sellerId": "seller-1",
      "sellerName": "AutoPrime SP",
      "categoryId": "vehicles",
      "categoryName": "Vehicles",
      "price": 22900,
      "images": [
        "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Low mileage motorcycle, second key and manual included, documents current.",
      "condition": "Used",
      "location": "Belo Horizonte, MG",
      "status": "Active"
    },
    {
      "id": "12356",
      "slug": "dining-table-wood-12356",
      "title": "Solid Wood Dining Table with 6 Chairs",
      "sellerId": "seller-4",
      "sellerName": "Casa Viva Curitiba",
      "categoryId": "home",
      "categoryName": "Home & Garden",
      "price": 2400,
      "images": [
        "https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1000&q=85"
      ],
      "description": "Well-kept dining set with six matching chairs and a timeless natural finish.",
      "condition": "Used",
      "location": "Curitiba, PR",
      "status": "Active"
    }
  ],
  "sellers": [
    {
      "id": "seller-1",
      "name": "AutoPrime SP",
      "owner": "",
      "avatar": "https://i.pravatar.cc/160?img=12",
      "verified": true,
      "rating": 4.9,
      "memberSince": "March 2022",
      "location": "São Paulo, SP",
      "plan": "",
      "status": "Verified"
    },
    {
      "id": "seller-2",
      "name": "Mariana Costa",
      "owner": "",
      "avatar": "https://i.pravatar.cc/160?img=47",
      "verified": true,
      "rating": 4.8,
      "memberSince": "August 2023",
      "location": "Rio de Janeiro, RJ",
      "plan": "",
      "status": "Verified"
    },
    {
      "id": "seller-3",
      "name": "Tech House Campinas",
      "owner": "",
      "avatar": "https://i.pravatar.cc/160?img=33",
      "verified": false,
      "rating": 4.6,
      "memberSince": "January 2024",
      "location": "Campinas, SP",
      "plan": "",
      "status": "Pending"
    },
    {
      "id": "seller-4",
      "name": "Casa Viva Curitiba",
      "owner": "",
      "avatar": "https://i.pravatar.cc/160?img=18",
      "verified": true,
      "rating": 4.9,
      "memberSince": "November 2022",
      "location": "Curitiba, PR",
      "plan": "",
      "status": "Verified"
    }
  ],
  "plans": [
    {
      "id": "free",
      "name": "Free",
      "price": "R$ 0,00",
      "period": "/month",
      "listingLimit": "5",
      "featured": "0",
      "badge": ""
    },
    {
      "id": "basic",
      "name": "Basic",
      "price": "R$ 39,90",
      "period": "/month",
      "listingLimit": "25",
      "featured": "0",
      "badge": ""
    },
    {
      "id": "pro",
      "name": "Pro",
      "price": "R$ 89,90",
      "period": "/month",
      "listingLimit": "100",
      "featured": "0",
      "badge": ""
    },
    {
      "id": "business",
      "name": "Business",
      "price": "R$ 199,90",
      "period": "/month",
      "listingLimit": "300",
      "featured": "0",
      "badge": ""
    }
  ],
  "promotionProducts": [
    {
      "id": "featured",
      "name": "Featured",
      "price": "R$ 19,90",
      "description": "Stand out with a premium Featured badge and stronger placement.",
      "duration": ""
    },
    {
      "id": "top_search",
      "name": "Top of Search",
      "price": "R$ 14,90",
      "description": "Move higher in relevant search results for more discovery.",
      "duration": ""
    },
    {
      "id": "urgent",
      "name": "Urgent",
      "price": "R$ 9,90",
      "description": "Add an Urgent badge to attract buyers who are ready to act.",
      "duration": ""
    },
    {
      "id": "homepage",
      "name": "Homepage Featured",
      "price": "R$ 29,90",
      "description": "Eligible for premium placement on the Marketlift homepage.",
      "duration": ""
    }
  ],
  "reportReasons": [
    "account",
    "payment",
    "moderation",
    "safety",
    "technical",
    "other"
  ],
  "listingConditions": [
    "New",
    "Like new",
    "Used"
  ],
  "verificationDocumentTypes": [
    "National ID",
    "Driver's licence",
    "Passport"
  ],
  "locations": [
    {
      "code": "SP",
      "name": "São Paulo",
      "cities": [
        "São Paulo",
        "Campinas",
        "Guarulhos",
        "Santos",
        "Ribeirão Preto",
        "Sorocaba"
      ]
    },
    {
      "code": "RJ",
      "name": "Rio de Janeiro",
      "cities": [
        "Rio de Janeiro",
        "Niterói",
        "Duque de Caxias",
        "Nova Iguaçu",
        "Petrópolis"
      ]
    },
    {
      "code": "MG",
      "name": "Minas Gerais",
      "cities": [
        "Belo Horizonte",
        "Uberlândia",
        "Contagem",
        "Juiz de Fora",
        "Betim"
      ]
    },
    {
      "code": "BA",
      "name": "Bahia",
      "cities": [
        "Salvador",
        "Feira de Santana",
        "Vitória da Conquista",
        "Camaçari"
      ]
    },
    {
      "code": "PR",
      "name": "Paraná",
      "cities": [
        "Curitiba",
        "Londrina",
        "Maringá",
        "Ponta Grossa"
      ]
    },
    {
      "code": "RS",
      "name": "Rio Grande do Sul",
      "cities": [
        "Porto Alegre",
        "Caxias do Sul",
        "Canoas",
        "Pelotas"
      ]
    },
    {
      "code": "PE",
      "name": "Pernambuco",
      "cities": [
        "Recife",
        "Jaboatão dos Guararapes",
        "Olinda",
        "Caruaru"
      ]
    },
    {
      "code": "GO",
      "name": "Goiás",
      "cities": [
        "Goiânia",
        "Aparecida de Goiânia",
        "Anápolis",
        "Rio Verde"
      ]
    },
    {
      "code": "DF",
      "name": "Distrito Federal",
      "cities": [
        "Brasília",
        "Taguatinga",
        "Ceilândia",
        "Águas Claras"
      ]
    }
  ]
} as const;

export type MarketplaceDomainSnapshot = typeof marketplaceDomain;
